table f_MateriaisAplicados
	lineageTag: c9edd4f3-3508-4a0b-85d4-04ac6d758f37

	measure _ConsumoMédioMês = ```
			
			    VAR TabelaFiltrada = 
			        CALCULATETABLE(
			            DISTINCT(
			                SELECTCOLUMNS(
			                    'f_MateriaisAplicados',
			                    "MesRef", DATE(YEAR('f_MateriaisAplicados'[Data Aplicação]), 
			                                   MONTH('f_MateriaisAplicados'[Data Aplicação]), 1)
			                )
			            )
			        )  
			    VAR _MesesFiltrados = COUNTROWS(TabelaFiltrada)
			    VAR qtdAplic = SUM(f_MateriaisAplicados[Qtde. Aplic.])
			
			    RETURN
			    IF(
			        _MesesFiltrados = 0,
			        BLANK(),
			        DIVIDE(qtdAplic, _MesesFiltrados, 0)
			    )
			```
		lineageTag: cbbd176e-1844-4892-93ea-1742d103d962

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_qtd. Aplic. Mes Anterior' = ```
			
			VAR MesAnterior = CALCULATE(
			    SUM(f_MateriaisAplicados[Qtde. Aplic.]), 
			    DATEADD('d_Calendário'[Data], -1, MONTH)
			)
			RETURN
			MesAnterior
			```
		lineageTag: 8150b30a-3332-4d74-b7c0-1c686aca257f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Diferença MoM %' =
			
			VAR MesAtual = SUM(f_MateriaisAplicados[Qtde. Aplic.])
			VAR MesAnterior = [_qtd. Aplic. Mes Anterior]
			VAR CalcDiffMes = DIVIDE( MesAtual - MesAnterior, MesAnterior, 0 )
			RETURN
			CalcDiffMes
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a16e2562-7cdb-476e-a499-ada38f8e21b4

	measure '_% do total serv.' = ```
			
			/*VAR MesAtual = SUM(f_MateriaisAplicados[Qtde. Aplic.])
			VAR TotalMes = CALCULATE(
			    SUM(f_MateriaisAplicados[Qtde. Aplic.]),
			    REMOVEFILTERS(f_MateriaisAplicados[d_DE-PARA-SERVIÇO.CATEGORIA]),
			    REMOVEFILTERS(f_MateriaisAplicados[d_DE-PARA-TECNOLOGIA.CATEGORIA])
			)
			RETURN
			DIVIDE( MesAtual, TotalMes, 0 )*/
			
			VAR totalmes = CALCULATE(
			    SUM(f_MateriaisAplicados[Qtde. Aplic.]), 
			    /*ALLEXCEPT(
			        f_MateriaisAplicados,
			        f_MateriaisAplicados[DataHora Aplicacao],
			        f_MateriaisAplicados[Serializado?],
			        f_MateriaisAplicados[Condição],
			        f_MateriaisAplicados[Material],
			        f_MateriaisAplicados[Cód. Material],
			        f_MateriaisAplicados[Projeto]
			    ),*/
			    KEEPFILTERS('d_Calendário'),
			    REMOVEFILTERS(f_MateriaisAplicados[d_DE-PARA-TECNOLOGIA.CATEGORIA]),
			    REMOVEFILTERS(f_MateriaisAplicados[d_DE-PARA-SERVIÇO.CATEGORIA])
			)
			RETURN
			
			DIVIDE(SUM(f_MateriaisAplicados[Qtde. Aplic.]), totalmes, 0)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 64b65f6b-7066-4121-90e6-71e3c9046c1d

	measure 'SUM qtd aplic' = SUM(f_MateriaisAplicados[Qtde. Aplic.])
		lineageTag: 3a7b967d-5f22-4b65-981e-e5e7c393a26b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Entregue/Aplic' =
			
			
			
			DIVIDE([SUM qtd aplic]+[_Qtd_Devolvida_REAP+NOVO], [_Qtd_Requisitada], 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 8ed0381e-b6fe-4b35-96fc-e81cf488295a

	column Contrato
		dataType: string
		lineageTag: 18db7fa0-f3e3-4090-83e5-399b18247959
		summarizeBy: none
		sourceColumn: Contrato

		annotation SummarizationSetBy = Automatic

	column Projeto
		dataType: string
		lineageTag: 37e1e435-b3cb-4c70-b10d-25b57b30e7cc
		summarizeBy: none
		sourceColumn: Projeto

		annotation SummarizationSetBy = Automatic

	column 'Cód. Equipe'
		dataType: int64
		formatString: 0
		lineageTag: 14ff0feb-d1b5-4afc-814a-16011deaf9ec
		summarizeBy: none
		sourceColumn: Cód. Equipe

		annotation SummarizationSetBy = Automatic

	column Equipe
		dataType: string
		lineageTag: 150fb02b-2cad-440d-a38e-c3c698126f2c
		summarizeBy: none
		sourceColumn: Equipe

		annotation SummarizationSetBy = Automatic

	column Município
		dataType: string
		lineageTag: af285d42-043f-4a9e-827d-52ceeea05566
		summarizeBy: none
		sourceColumn: Município

		annotation SummarizationSetBy = Automatic

	column 'Nº Cliente'
		dataType: int64
		formatString: 0
		lineageTag: b82c8ae2-8d1c-43d5-998d-c6b751ecfd59
		summarizeBy: sum
		sourceColumn: Nº Cliente

		annotation SummarizationSetBy = Automatic

	column 'Nome do Cliente'
		dataType: string
		lineageTag: 6ccce8b2-a3b8-4cdd-ac33-fb5b95562dbf
		summarizeBy: none
		sourceColumn: Nome do Cliente

		annotation SummarizationSetBy = Automatic

	column OS
		dataType: string
		lineageTag: 743324b2-22e1-4bb0-8805-ad9399012090
		summarizeBy: none
		sourceColumn: OS

		annotation SummarizationSetBy = Automatic

	column 'Data Aplicação'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 6be0b60d-6be1-40ab-8063-97ca5a34fbf3
		summarizeBy: none
		sourceColumn: Data Aplicação

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Desc. Tipo Serv.'
		dataType: string
		lineageTag: 1be0b32c-ecab-4c48-af58-2c678eb2752d
		summarizeBy: none
		sourceColumn: Desc. Tipo Serv.

		annotation SummarizationSetBy = Automatic

	column 'Cód. Material'
		dataType: string
		lineageTag: 242a8349-a3c3-4b9f-9c23-70aafb11310e
		summarizeBy: none
		sourceColumn: Cód. Material

		annotation SummarizationSetBy = Automatic

	column Material
		dataType: string
		lineageTag: 517dec9a-4ec7-4f35-960c-7614347a3830
		summarizeBy: none
		sourceColumn: Material

		annotation SummarizationSetBy = Automatic

	column 'N° Serie'
		dataType: string
		lineageTag: 4491313c-408a-4219-9e13-629a45357ab4
		summarizeBy: none
		sourceColumn: N° Serie

		annotation SummarizationSetBy = Automatic

	column 'Qtde. Aplic.'
		dataType: double
		formatString: #,0
		lineageTag: 4e397826-bbf7-4a0d-b0b2-f6946230d4df
		summarizeBy: sum
		sourceColumn: Qtde. Aplic.

		annotation SummarizationSetBy = Automatic

	column 'Qtde. Remov.'
		dataType: int64
		formatString: 0
		lineageTag: 49f3b333-3b69-4400-9724-c23f75cc9fb1
		summarizeBy: sum
		sourceColumn: Qtde. Remov.

		annotation SummarizationSetBy = Automatic

	column Natureza
		dataType: string
		lineageTag: c345774f-4cf6-48a1-b1a2-bd812daa7de4
		summarizeBy: none
		sourceColumn: Natureza

		annotation SummarizationSetBy = Automatic

	column Usuário
		dataType: string
		lineageTag: 4983690b-63ea-4e67-a588-da4796438aca
		summarizeBy: none
		sourceColumn: Usuário

		annotation SummarizationSetBy = Automatic

	column 'd_DE-PARA-SERVIÇO.CATEGORIA'
		dataType: string
		lineageTag: df750def-ac80-4375-959d-9b6ccc6a73ee
		summarizeBy: none
		sourceColumn: d_DE-PARA-SERVIÇO.CATEGORIA

		annotation SummarizationSetBy = Automatic

	column Condição
		dataType: string
		lineageTag: 62bf4098-f5c1-45e3-8de8-7846c9565029
		summarizeBy: none
		sourceColumn: Condição

		annotation SummarizationSetBy = Automatic

	column Serializado?
		dataType: string
		lineageTag: 1605ded1-e89d-4b2a-9cbf-24a86e7c1974
		summarizeBy: none
		sourceColumn: Serializado?

		annotation SummarizationSetBy = Automatic

	column 'd_DE-PARA-TECNOLOGIA.CATEGORIA'
		dataType: string
		lineageTag: 01fce0d0-250c-4133-a4c3-655f372ae6db
		summarizeBy: none
		sourceColumn: d_DE-PARA-TECNOLOGIA.CATEGORIA

		annotation SummarizationSetBy = Automatic

	column 'DataHora Aplicacao'
		dataType: dateTime
		formatString: General Date
		lineageTag: 7351b148-0965-46ce-a9c0-8b3f04893cef
		summarizeBy: none
		sourceColumn: DataHora Aplicacao

		variation Variation
			isDefault
			relationship: f2b75004-c6bb-41c1-8b75-b81843217106
			defaultHierarchy: LocalDateTable_80071d68-f2ab-463c-a0f9-bbd572bc9109.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Plano Velocidade' =
			
			VAR OSAtual = f_MateriaisAplicados[OS]
			RETURN
			COALESCE(
			CALCULATE(
			    CONCATENATEX(
			        DISTINCT('f_Solicitacoes'[Velocidade Agrupada]),
			        'f_Solicitacoes'[Velocidade Agrupada],
			        " | "
			    ),
			    FILTER(
			        ALL('f_Solicitacoes'),
			        'f_Solicitacoes'[Nº. Ordem Serviço] = OSAtual
			    )
			), "NÃO IDENTIFICADO")
		dataType: string
		lineageTag: 0dfb0b54-e58e-4dba-a242-b1848763b0ae
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Bruto Velocidade' =
			
			VAR OSAtual = f_MateriaisAplicados[OS]
			RETURN
			COALESCE(
			CALCULATE(
			    CONCATENATEX(
			        DISTINCT('f_Solicitacoes'[Observação]),
			        'f_Solicitacoes'[Observação],
			        " | "
			    ),
			    FILTER(
			        ALL('f_Solicitacoes'),
			        'f_Solicitacoes'[Nº. Ordem Serviço] = OSAtual
			    )
			), "NÃO IDENTIFICADO")
		lineageTag: b2e9e691-1267-400e-b09e-f1489a248bc4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Plano VelocidadeB' = ```
			
			
			--- CÓDIGO TEMPORARIO, TROCAR POR MINX OU REMOVER DUPLICATAS NUM OS ----
			/*
			VAR Velocidade = 
			    CALCULATE(
			        CONCATENATEX(
			            DISTINCT('f_Solicitacoes'[Velocidade do Plano]),
			            'f_Solicitacoes'[Velocidade do Plano],
			            ""
			        ),
			        FILTER(
			            ALL('f_Solicitacoes'),
			            'f_Solicitacoes'[Nº. Ordem Serviço] = f_MateriaisAplicados[OS]
			        )
			    )
			RETURN
			
			IF(
			    Velocidade <> "" && velocidade <> BLANK(),
			    Velocidade, 
			    BLANK()
			)
			*/
			
			VAR vOS = f_MateriaisAplicados[OS]
			
			VAR Velocidade = 
			    CALCULATE(
			        MAX('f_Solicitacoes'[Velocidade do Plano]),
			        FILTER(
			            ALL('f_Solicitacoes'[Nº. Ordem Serviço]),
			            'f_Solicitacoes'[Nº. Ordem Serviço] = vOS
			        )
			    )
			RETURN
			    Velocidade
			```
		dataType: int64
		formatString: 0
		lineageTag: 6179d121-0ce8-4433-bb1b-786efa645ef1
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'OTIMIZAÇÃO APLICAÇÃO' = ```
			
			VAR velocidade = f_MateriaisAplicados[Plano VelocidadeB]
			RETURN
			
			SWITCH(
			    TRUE(),
			    velocidade > 0 && velocidade < 300, "WIFI 5", 
			    velocidade >= 300 && Velocidade <= 10000, "WIFI 6",
			    "SEM INFORMAÇÃO PLANO"
			)
			```
		lineageTag: 92e04dd0-0f7b-4d52-a3ec-510288690e16
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Plano/Produto =
			
			VAR OSAtual = f_MateriaisAplicados[OS]
			RETURN
			COALESCE(
			CALCULATE(
			    CONCATENATEX(
			        DISTINCT('f_Solicitacoes'[Observação]),
			        'f_Solicitacoes'[Observação],
			        " | "
			    ),
			    FILTER(
			        ALL('f_Solicitacoes'),
			        'f_Solicitacoes'[Nº. Ordem Serviço] = OSAtual
			    )
			), "NÃO IDENTIFICADO")
		lineageTag: 7c0ad193-926a-44b4-84bb-de517caa5279
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition f_MateriaisAplicados = m
		mode: import
		queryGroup: 'Tabelas Principais'
		source = ```
				let 
				    Fonte = Folder.Files(#"Pasta Raiz" & "\Materiais Aplicados & Retirados"),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(Fonte, each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo", each #"Transformar Arquivo"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1",{"Transformar Arquivo"}),
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo", Table.ColumnNames(#"Transformar Arquivo"(#"Arquivo de Amostra"))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna de Tabela Expandida1",{{"Contrato", type text}, {"Projeto", type text}, {"Cód. Equipe", Int64.Type}, {"Equipe", type text}, {"Município", type text}, {"Nº Cliente", Int64.Type}, {"Nome do Cliente", type text}, {"OS", type text}, {"Data Aplicação", type date}, {"Desc. Tipo Serv.", type text}, {"Cód. Material", type text}, {"Material", type text}, {"N° Serie", type text}, {"Qtde. Aplic.", type number}, {"Qtde. Remov.", Int64.Type}, {"Hora", type time}, {"Data", type date}, {"Usuário", type text}}),
				    
				    // Filtro Ajustado
				    /*
				    #"Filtro de materiais" = Table.SelectRows(#"Tipo Alterado", each 
				        (
				            [Data Aplicação] <= #date(2025, 12, 31) and 
				            Record.Field(_, "N° Serie") <> null and 
				            Record.Field(_, "N° Serie") <> "-"
				        ) 
				        or 
				        (
				            [Data Aplicação] >= #date(2026, 1, 1)
				        )
				    ),
				    
				    #"Linhas Filtradas1" = Table.SelectRows(#"Filtro de materiais", each [#"Qtde. Aplic."] > 0),
				    */
				
				    #"Linhas Filtradas1" = Table.SelectRows(#"Tipo Alterado", each [#"Qtde. Aplic."] > 0),
				
				    #"Texto Extraído Antes do Delimitador" = Table.TransformColumns(#"Linhas Filtradas1", {{"OS", each Text.BeforeDelimiter(_, "/"), type text}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Texto Extraído Antes do Delimitador",{{"Data", "Data Inclusão Material"}}),
				
				
				    // Criando a coluna de Condição Aplicada (Lógica 1)
				    Condição = Table.AddColumn(#"Colunas Renomeadas", "Condição", each 
				    let 
				        Cod = Text.Upper(Text.From([Material])) 
				    in
				        if Text.Contains(Cod, "DEF-") or Text.Contains(Cod, "DET-") then "DEFEITO"
				        else if Text.Contains(Cod, "RET-") then "RETIRADO"
				        else if Text.Contains(Cod, "REAP-") or Text.Contains(Cod, "REA-") then "REAPROVEITADO"
				        else if Text.Contains(Cod, "SUC-") then "DESUSO"
				        else if [Material] <> null and [Material] <> "" then "NOVO"
				        else "VAZIO"
				    ),
				
				    // Criando a coluna de Verificação de N° de Série (Lógica 2)
				    NumSerie = Table.AddColumn(#"Condição", "Serializado?", each 
				        if [#"N° Serie"] = null or [#"N° Serie"] = "-" or [#"N° Serie"] = "" then "NÃO" 
				        else "SIM"
				    ),
				    #"Consultas Mescladas" = Table.NestedJoin(NumSerie, {"Desc. Tipo Serv."}, #"d_DE-PARA-SERVIÇO", {"DESC. TIPO SERV."}, "d_DE-PARA-SERVIÇO", JoinKind.LeftOuter),
				    #"d_DE-PARA-SERVIÇO Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "d_DE-PARA-SERVIÇO", {"CATEGORIA"}, {"d_DE-PARA-SERVIÇO.CATEGORIA"}),
				    #"Valor Substituído" = Table.ReplaceValue(#"d_DE-PARA-SERVIÇO Expandido",null,"NÃO MAPEADO",Replacer.ReplaceValue,{"d_DE-PARA-SERVIÇO.CATEGORIA"}),
				    #"Consultas Mescladas1" = Table.NestedJoin(#"Valor Substituído", {"Material"}, #"d_DE-PARA-TECNOLOGIA", {"EQUIPAMENTO"}, "d_DE-PARA-TECNOLOGIA", JoinKind.LeftOuter),
				    #"d_DE-PARA-TECNOLOGIA Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas1", "d_DE-PARA-TECNOLOGIA", {"CATEGORIA"}, {"d_DE-PARA-TECNOLOGIA.CATEGORIA"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"d_DE-PARA-TECNOLOGIA Expandido",null,"NÃO MAPEADO",Replacer.ReplaceValue,{"d_DE-PARA-TECNOLOGIA.CATEGORIA"}),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Valor Substituído1",{"Contrato", "Projeto", "Cód. Equipe", "Equipe", "Município", "Nº Cliente", "Nome do Cliente", "OS", "Data Aplicação", "Desc. Tipo Serv.", "Cód. Material", "Material", "N° Serie", "Qtde. Aplic.", "Qtde. Remov.", "Natureza", "Hora", "Data Inclusão Material", "Usuário", "d_DE-PARA-SERVIÇO.CATEGORIA", "Condição", "Serializado?", "d_DE-PARA-TECNOLOGIA.CATEGORIA"}),
				    #"Erros Substituídos" = Table.ReplaceErrorValues(#"Colunas Reordenadas", {{"Condição", "VAZIO"}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Erros Substituídos", "DataHora Aplicacao", each DateTime.From(Text.From([Data Inclusão Material]) & " " & Text.From([Hora]))),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Personalização Adicionada",{{"DataHora Aplicacao", type datetime}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado1",{"Hora", "Data Inclusão Material"})
				in
				    #"Colunas Removidas"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

